### ISSUE TITLE
create font stack for rendering

### ISSUE THREAD

**Issue by flying-sheep** [lautis/emojie#4]
this is awesome!

a useful extension would be to wrap emojis in a `<span class=emoji/>` first and try to render it like this, and only then fall back.

the class would have a font stack like this:

``` css
.emoji {
    font-family: "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", OpenSansEmoji, EmojiSymbols, EmojiSymb, Symbola;
}
```
